application: dalieveligden
version: 2
runtime: python
api_version: 1

handlers:
- url: /media
  static_dir: media

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /.*
  script: main.py
